root: true

env:
  commonjs: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 8

rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  indent: [error, 2, { SwitchCase: 1 }]
  no-trailing-spaces: error
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]
